Live from Processing Day!
CodingTrain/CommunityClouds pull request #67
Opened 2017-10-21 19:10 UTC by shiffman

Stil live from Processing day. This is a cloud that I made as an example.

2017-10-21 19:10 UTC, shiffman commented on generators.js
> +  let stepsize = 5;
maybe you should learn about const?

2017-10-21 19:14 UTC, meiamsome commented
Looks like you need to set angle mode to degrees!

2017-10-21 19:34 UTC, meiamsome requested changes
Needs an explicit `angleMode(DEGREES)` at the top of the function!

2017-10-22 13:59 UTC, shiffman commented
Ok, I added `angleMode(DEGREES)` and also moved the function below the example, thanks for reviewing!

2017-10-22 17:36 UTC, merged